---
- stat: path="{{ php_config_prefix }}/apache2/php.ini"
  register: modphp

- stat: path="{{ php_config_prefix }}/fpm/php.ini"
  register: phpfpm

- stat: path="{{ php_config_prefix }}/cli/php.ini"
  register: phpcli

- import_tasks: php-fpm.yml
  when: phpfpm.stat.exists

- import_tasks: php-cli.yml
  when: phpcli.stat.exists

- import_tasks: mod-php.yml
  when: modphp.stat.exists
