---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Ensure packages database is up to date
  become: yes
  apt: update_cache=yes

- name: Install php
  become: yes
  apt: pkg="php{{ php_version }}" state=latest

- name: Install php-fpm
  become: yes
  apt: pkg="php{{ php_version }}-fpm" state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg=php{{ php_version }}-{{ item }} state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined

- include: configure.yml

- include: pecl.yml
